### ISSUE TITLE
Data.Store.map fails to update index.

### ISSUE THREAD

**Issue by MichaelXavier** [Palmik/data-store#3]
I haven't yet produced a minimal test case as my application is fairly complex, but here's the gist:

I'm using Storable to create a table for a record I have. The record has a field watchWState that is essentially defined as Active Int | Notifying.

If I do a map to update the state to Notifying from Active, if I do a query like S.lookup (sWatchWState .== Notifying) table, it comes back with nothing. Showing the raw table shows that the value of the row has Notifying, but the key portion still has the original value.

I can't imagine this is expected behavior. Maps by definition will update the records, so its weird that you cannot query the new table by the new values. It seems like the code https://github.com/Palmik/data-store/blob/master/src/Data/Store.hs#L445 just passes the key straight through.

In the mean time i guess I can do something like (S.fromList . Data.List.map . S.toList).

**Comment by Palmik** [comment]
Hi Michael. This is actually intended as keys and elements are in case of `data-store` separate entities. Generally you could use `updateWithKey` or `updateWithKey'` to update the elements and their keys at the same time. Also note that `Data.Store.map` is much more lightweight than `Data.Store.updateWithKey` since it does not cause reindexing of any elements.

In your case, since you are using `Data.Store.Storable`, you should use `Data.Store.Storable.update` or `Data.Store.Storable.update'` which indeed keep the elements and their keys synchronized (using the user defined `Data.Store.Storable.Storable.key` function).

I will probably provide a convenience functions `Data.Store.Storable.map` and `Data.Store.Storable.map'`, but those will be just a versions of `Data.Store.Storable.update` and `Data.Store.Storable.update'` respectively that work on the whole store.

**Comment by MichaelXavier** [comment]
Hi,

Interesting. I'm thinking the documentation of map should probably reflect that it does not update the keys. It was definitely surprising to me to do an update then not be able to query on the result. Just out of curiosity, what is the use case for an update that does not update the keys. Is the idea that whenever you do this, your intent is to turn the datastore into a list with `elements` so the keys are irrelevant? I'm just having trouble imagining what the use case could be.

I'm cool with using `update'` for this, but I'm curious how I'd basically make an unqualified selection such that every element satisfies it. I noticed the documentation for `Data.Store.Selection.all` says "everything if the list is empty", but the implementation is: `all []  = error $ moduleName <> ".all: empty list."`, so I don't think I could actually make this query.

**Comment by Palmik** [comment]
Hi, `data-store` is modeled after associative containers from `containers` and `unordered-containers`, where keys and elements are also separate entities and thus `map` does not affect the keys, therefore it is also the case for `data-store`. 

In some cases it is not possible to derive the key from the element alone (such as when you have to consult the outside world (i.e. `IO`) to obtain the whole key (e.g. query the database or generate some random bytes)) -- you could of course store this information in the element data type beforehand, but it's not always the most elegant solution.

Anyway. I have fixed the documentation (of `all`, `all1D`, `any` and `any1D`) so that it reflects the implementation. I have also made some minor updates to the overall documentation that warns the user (at appropriate places) about the implications of using update functions that are outside of the `Data.Store.Storable` module. Hopefully this should clear things up.

Finally, I have added `Data.Store.Storable.map` function that is implemented much like `Data.Store.Storable.update'`. So far it's implemented as a "quick hack", but I will provide cleaner implementation in the future (this should not affect the users in any noticeable way).

**Comment by MichaelXavier** [comment]
Cool. That all seems quite reasonable. Thanks! I think I was conceptualizing the whole data-store library with the semantics of Storable, which links the data to the keys. I'm excited to use Data.Store.Storable.map to get rid of the ugliness I put into my code to work around. Thanks!
